Prefix: '&6&lT3SL4Claim &8» '
Settings:
  DisplaySlot: 22
  Border:
    material: 'GLASS'
  ClaimBlock:
    material: 'BEDROCK'
  enabled-worlds:
    - 'world'
    - 'Orman'
  prices:
    TL:
      value: 15000
    kredi:
      value: 10
    coinType:
      value: 25
World:
  world: "&eWorld: &f"
  X: "&eX: &f"
  Z: "&eZ: &f"
  claim: "&eClaim No: &f"
  splitter: " &7-> "
Info:
  Commands:
    - '&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m[&6 &lT3SL4Claim &8&l&m]&f&l&m-&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m-'
    - '&a/claim menu &f»&eOpen the claim menu.'
    - '&a/claim add &bOyuncu &f»&eAdd player to claim.'
    - '&a/claim remove &bOyuncu &f»&eRemove player to claim.'
    - '&a/claim info &f»&eIndicates nearby claims.'
    - '&a/claim query &f»&eShow the remaining time of claim.'
    - '&a/claim staffs &f»&eShows the authorized player of claim.'
    - '&a/claim list &f»&eShow ur claims.'
    - "&a/claim chunk &f»&eShows the limit of chunk you're in."
    - '&a/claim opmode &f»&eTurn on / off the op mode for claims.'
    - '&a/claim reload &f»&eReload plugin.'
  PlayerCommands:
    - '&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m[&6 &lT3SL4Claim &8&l&m]&f&l&m-&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m-'
    - '&a/claim menu &f»&eOpen the claim menu.'
    - '&a/claim add &bOyuncu &f»&eAdd player to claim.'
    - '&a/claim remove &bOyuncu &f»&eRemove player to claim.'
    - '&a/claim info &f»&eIndicates nearby claims.'
    - '&a/claim query &f»&eShow the remaining time of claim.'
    - '&a/claim staffs &f»&eShows the authorized player of claim.'
    - '&a/claim list &f»&eShow ur claims.'
    - "&a/claim chunk &f»&eShows the limit of chunk you're in."
Messages:
  has-not-value: "&4You dont have enough: &e%value%"
  claim-disabled-world: "&4Claims can not be taken in this world!"
  claim-end: "&eClaim number &a%claim% &eof player &b%player% &ehas finished. &7(&c%location%&7)"
  chunk-already-claimed: "&4This area is already claimed !"
  claim-time-changed: "&eClaim has been extended until &b%time% &e!"
  claim-set: "&aYour area has been successfully claimed !"
  unknown-error: "&4Unknown error occurred. Please try again later !"
  claim-info: "&eYou claim that &b%player% &ehas had for &a%time%&e!"
  you-are-not-staff: "&4You are not authorized in this claim.!"
  he-already-staff: "&4This player is already authorized!"
  he-not-staff: "&4This player is not already authorized!"
  staff-added: "&b%player% &ehas been added to claim!"
  staff-removed: "&b%player% &eremoved from claim!"
  staff-list: "&eStaffs at this claim: &b%staffs-'&a,&f'%"
  claim-list: "&eYour claims: &b%claims-'&a,&f'%"
  unknown-claim: "&4No claim where you are!"
  chunk-viewed: "&eGlasses around it mark chunk boundaries in your area !"
  chunk-removed: "&eThe glasses around you removed because you move!"
  console: "&4You can not use this command from console!"
  error-cmd: "&4You dont have permission to use this command!"
  reload: "&aPlugin reload successfull!"
  opmode-close: "&eOp mode has been de-activated."
  opmode-open: "&eOp mode has been activated."