name: T3SL4Claim
author: [SYN_T3SL4]
version: 17.02.2021
main: me.t3sl4.claim.T3SL4Claim
description: A claim plugin
depend: [Vault, HolographicDisplays]
softdepend: [T3SL4Kredi, Skript]

commands:
  claim:
    description: The main command of T3SL4Claim.
    aliases: [sahiplen]
